import esbuild from "esbuild";
import process from "process";
import { readFileSync } from "fs";
import { builtinModules } from "node:module";

// The standalone server: the plugin's request handling, with the "obsidian"
// module it imports replaced by the filesystem-backed one in src/standalone.
// Everything is bundled into one file, so the runtime image needs no
// node_modules.

const prod = process.argv[2] === "production";
const { version } = JSON.parse(readFileSync("package.json", "utf8"));

const buildOptions = {
  banner: {
    js: "/* obsidian-remote-rest-api: generated by esbuild from src/standalone/server.ts */",
  },
  entryPoints: ["src/standalone/server.ts"],
  bundle: true,
  platform: "node",
  alias: {
    obsidian: "./src/standalone/obsidian/index.ts",
  },
  // sharp loads a native library for the platform it runs on, so it is
  // installed in the image rather than bundled.
  external: ["sharp", ...builtinModules, ...builtinModules.map((name) => `node:${name}`)],
  define: {
    STANDALONE_VERSION: JSON.stringify(version),
  },
  format: "cjs",
  target: "node22",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/server.js",
  loader: {
    ".yaml": "text",
  },
};

if (prod || process.argv[2] === "once") {
  esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
}
